# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

        bind:
            $notificationSender: '@rabbit_mq_notificator'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Domain/Model/'
            - '../src/Kernel.php'
            - '../src/Domain/Model/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    rabbit_mq_notificator:
        class: App\Application\SendNotification
        arguments:
            $notificator: '@App\Infrastructure\Domain\Service\RabbitMqNotificator'

    App\Infrastructure\Domain\Service\RabbitMqNotificator:
        arguments:
            $rabbitMqService: '@rabbit_mq_test_messages'

