FROM httpd:2.4
#FROM sgadpsf/apache-2.4.10:latest

RUN apt-get -y update
RUN apt-get -y install libapache2-mod-php

#RUN apt-get update && apt-get install -y \
#    && docker-php-ext-install pdo pdo_mysql \
#    && docker-php-ext-enable pdo pdo_mysql

EXPOSE 80

